env:
  browser: true
  es2021: true
extends:
  - 'react-app'
  - 'react-app/jest'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
ignorePatterns:
  - libs/*
rules:
  indent:
    - error
    - 2

  linebreak-style:
    - error
    - unix

  quotes:
    - error
    - single

  semi:
    - error
    - always

  brace-style:
    - error
    - stroustrup
    -
      allowSingleLine: true

  comma-dangle:
  - error
  - always-multiline

  no-use-before-define: off

  react/jsx-uses-react: off
  react/react-in-jsx-scope: off

  object-curly-spacing:
    - error
    - always
